format = '''
\[$username$hostname $directory$git_branch$git_commit$git_state$git_status\]\$ '''

scan_timeout = 10
add_newline = false

[line_break]
disabled = true

[username]
style_user = "yellow bold"
style_root = "red bold"
format = "[$user]($style) "
show_always = true

[package]
disabled = false

[hostname]
ssh_only = false
format = '@ [$hostname](bold red) '

[directory]
read_only = " "
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"
