add_newline = false

[line_break]
disabled = false

[character]                            
# this is kinda edgy ig
#success_symbol = "[](bold green)"    
#error_symbol = "[](bold red)"
#vicmd_symbol = "[](bold blue)"

[username]
style_user = "yellow bold"
style_root = "red bold"
format = "[$user]($style) "
show_always = true

[package]
disabled = false

[directory]
read_only = "  "
style = "bold blue"
truncation_length = 2
truncation_symbol = "./"
